routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\userManagementController;
use App\Http\Controllers\Admin\profileSettingsController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\VehicleController;
use App\Http\Controllers\Admin\TransactionController;

/* Admin Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
	
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('scan', [HomeController::class, 'scanner'])->name('scanner');
    Route::get('scan-code', [HomeController::class, 'scanCode'])->name('scanning');
 
    Route::group(['prefix' => 'users', 'as' => 'user_management.'], function(){
		Route::controller(userManagementController::class)->group(function () {
			Route::get('/manage/{type}', 'index')->name('index');
			Route::post('store', 'store')->name('store');
			Route::get('list/{type}', 'list')->name('list');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('destroy/{id?}', 'destroy')->name('destroy');
			Route::post('/upload', 'uploadFile')->name('upload.file');
		});
	});

	Route::group(['prefix' => 'profile-settings', 'as' => 'profile_settings.'], function(){
		Route::controller(profileSettingsController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('change_password', 'change_password')->name('change_password');
			Route::post('store', 'store')->name('store');
		});
	});

	Route::group(['prefix' => 'vehicles', 'as' => 'vehicles.'], function(){
		Route::controller(VehicleController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	Route::group(['prefix' => 'transactions', 'as' => 'transaction.'], function(){
		Route::controller(TransactionController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('download', 'generatePDF')->name('pdf');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');

		});
	});

	
});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'index'])->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');




//Authentications
Route::group(['prefix'=> 'auth'], function(){

    Route::name('auth.')->group(function () {
        // For Login
        Route::controller(AuthController::class)->group(function () {
             Route::post('request', 'authenticate')->name('authenticate');
             Route::get('forget-password', 'forget_password')->name('forget.password');
             Route::post('forget-password/submit', 'forget_password_submit')->name('forget.password.submit');
             Route::get('change-password/{token?}', 'change_password')->name('change.password');
             Route::post('change-password/submit', 'change_password_submit')->name('change.password.submit');
             Route::post('update_pass', 'update_pass')->name('update.password');
        });

        // // For Forgot Password
        // Route::controller(ForgotPasswordController::class)->group(function () {
        //     Route::get('forget-password', 'index')->name('forget.password.get');
        //     Route::post('forget-password','store')->name('forget.password.post');
        //     Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        //     Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
        //     Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
        //     Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
        // });
        
    });
}); 




?>

resources/views/forgot_password.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Forgot Password</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('img/logo.png') }}">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
</head>

<body class="hold-transition login-page">

    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="javascript:;" class="h4">Forgot Password</a>
            </div>
            <div class="card-body mt-1">
                @if(session('status'))
                <label class="text-center text-danger"> {{ session('status') }} </label>
                @endif
                 @if(session('success'))
                <label class="text-center text-success"> {{ session('success') }} </label>
                @endif
                @if(session('change_pass'))
                <label class="text-center text-success"><span><i class="far fa-check-circle"></i></span> {{ session('change_pass') }} </label>
                @endif
                <form id="login_form" method="POST" action="{{ route('auth.forget.password.submit') }}" novalidate>
                    @csrf
                    <div class="input-group">
                        <input type="text" class="form-control" name="email_address" placeholder="Enter your email address">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <label class="text-danger text-sm mb-3"> {{ json_decode(session('errors'), true)['email_address'][0] ?? '' }} </label>
                    <div class="row mt-3">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Forget Password</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
</body>

</html>

resources/views/index.blade.php
@if(auth()->check())
    <script type="text/javascript">
        window.location = "{{ url('dashboard') }}";
    </script>
@else @endif
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login</title>
  <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="javascript:;" class="h3">E-Despatching <br> Smart Tranportation</a>
    </div>
    <div class="card-body mt-1">
      @if(session('status'))
           <label class="text-center text-danger">  {{ session('status') }} </label>
      @endif
      @if(session('change_pass'))
           <label class="text-center text-success"><span><i class="far fa-check-circle"></i></span>  {{ session('change_pass') }} </label>
      @endif
      <form id="login_form" method="POST" action="{{ route('auth.authenticate') }}" novalidate>
        @csrf
        <div class="input-group">
          <input type="text" class="form-control" name="username" placeholder="Email address">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
         <label class="text-danger text-sm mb-3">  {{ json_decode(session('errors'), true)['username'][0] ?? '' }} </label>

        <div class="input-group">
          <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-eye" onclick="password_toggler(this, '#password');"></span>
            </div>
          </div>
        </div>
        <label class="text-danger text-sm">  {{ json_decode(session('errors'), true)['password'][0] ?? '' }} </label>
        <div>
        <a href="{{ route('auth.forget.password') }}">Forget Password?</a>
        </div>
        <div class="row mt-3">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Sign in</button>
          </div>
          <!-- /.col -->
        </div>

      </form>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
<script type="text/javascript">
    function password_toggler(_this, selector){
      $(_this).toggleClass('fa-eye fa-eye-slash')
      $(selector).attr('type', function(index, attr){
          return attr == 'text' ? 'password' : 'text';
      });
    }
</script>

</body>
</html>

resources/views/new_password.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Forgot Password</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">

    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
    <style type="text/css">
       
    </style>
</head>
<body class="hold-transition login-page">


<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">

            <a href="javascript:;" class="h4">Password Reset</a>
        </div>
        <div class="card-body mt-1">
            @if(session('status'))
                <label class="text-center text-danger">  {{ session('status') }} </label>
            @endif
            
            <form id="newPass_form" method="POST" action="{{ route('auth.update.password') }}" novalidate>
                @csrf
                <input value="{{$token}}" id="token" name="token" hidden>
                @if (Session::has('message'))
                    <div class="alert alert-default-danger"><span><i class="fas fa-exclamation-circle"></i></span> {{ Session::get('message') }}</div>
                @endif
                <div class="input-group">
                    <input type="password" class="form-control" placeholder="New password" id="password" name="password" value="">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <label class="text-danger text-sm mb-3">  {{ json_decode(session('errors'), true)['password'][0] ?? '' }} </label>

                <div class="input-group">
                    <input type="password" class="form-control" placeholder="Re-enter password" id="confirm_password" name="confirm_password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <label class="text-danger text-sm mb-3">  {{ json_decode(session('errors'), true)['confirm_password'][0] ?? '' }} </label>

                <div class="row mt-3">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">Reset Password</button>
                    </div>
                </div>

            </form>

        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>


</body>
</html>