routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\userManagementController;
use App\Http\Controllers\Admin\profileSettingsController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\VehicleController;
use App\Http\Controllers\Admin\TransactionController;

/* Admin Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
	
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('scan', [HomeController::class, 'scanner'])->name('scanner');
    Route::get('scan-code', [HomeController::class, 'scanCode'])->name('scanning');
 
    Route::group(['prefix' => 'users', 'as' => 'user_management.'], function(){
		Route::controller(userManagementController::class)->group(function () {
			Route::get('/manage/{type}', 'index')->name('index');
			Route::post('store', 'store')->name('store');
			Route::get('list/{type}', 'list')->name('list');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('destroy/{id?}', 'destroy')->name('destroy');
			Route::post('/upload', 'uploadFile')->name('upload.file');
		});
	});

	Route::group(['prefix' => 'profile-settings', 'as' => 'profile_settings.'], function(){
		Route::controller(profileSettingsController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('change_password', 'change_password')->name('change_password');
			Route::post('store', 'store')->name('store');
		});
	});

	Route::group(['prefix' => 'vehicles', 'as' => 'vehicles.'], function(){
		Route::controller(VehicleController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	Route::group(['prefix' => 'transactions', 'as' => 'transaction.'], function(){
		Route::controller(TransactionController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('download', 'generatePDF')->name('pdf');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');

		});
	});

	
});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'index'])->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');




//Authentications
Route::group(['prefix'=> 'auth'], function(){

    Route::name('auth.')->group(function () {
        // For Login
        Route::controller(AuthController::class)->group(function () {
             Route::post('request', 'authenticate')->name('authenticate');
             Route::get('forget-password', 'forget_password')->name('forget.password');
             Route::post('forget-password/submit', 'forget_password_submit')->name('forget.password.submit');
             Route::get('change-password/{token?}', 'change_password')->name('change.password');
             Route::post('change-password/submit', 'change_password_submit')->name('change.password.submit');
             Route::post('update_pass', 'update_pass')->name('update.password');
        });

        // // For Forgot Password
        // Route::controller(ForgotPasswordController::class)->group(function () {
        //     Route::get('forget-password', 'index')->name('forget.password.get');
        //     Route::post('forget-password','store')->name('forget.password.post');
        //     Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        //     Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
        //     Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
        //     Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
        // });
        
    });
}); 




?>

resources/views/admin/home.blade.php
@extends('admin.layout.app')
@section('title', 'Dashboard')

@section('content')
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        @if(auth()->user()->type !== 4)
          <div class="row">
            <div class="col-lg-7">
              <div class="row">
                <!-- ./col -->
                <div class="col-lg-12 col-12">
                  <!-- small box -->
                  <div class="small-box bg-info">
                    <div class="inner">
                      <h3>{{ getTransaction() }}</h3>
                      <p>Today's Transactions</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-list nav-icon"></i>
                    </div>
                  </div>
                </div>

               
                 <!-- ./col -->
                <div class="col-lg-4 col-6">
                  <!-- small box -->
                  <div class="small-box bg-primary">
                    <div class="inner">
                      <h3>{{ getUsersCount(2); }}</h3>
                      <p>Dispatcher Accounts</p>
                    </div>
                    <div class="icon">
                      <!-- <i class="fas fa-bus nav-icon"></i> -->
                      <i class="fas fa-people-arrows nav-icon"></i>
                    </div>
                  </div>
                </div>

                <!-- ./col -->
                <div class="col-lg-4 col-6">
                  <!-- small box -->
                  <div class="small-box bg-danger">
                    <div class="inner">
                      <h3>{{ getUsersCount(3); }}</h3>
                      <p>Monitor Accounts</p>
                    </div>
                    <div class="icon">
                      <!-- <i class="fas fa-bus nav-icon"></i> -->
                      <i class="fas fa-user-shield nav-icon"></i>
                    </div>
                  </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                  <!-- small box -->
                  <div class="small-box bg-success">
                    <div class="inner">
                      <h3>{{ getUsersCount(4); }}</h3>
                      <p>Driver Accounts</p>
                    </div>
                    <div class="icon">
                      <!-- <i class="fas fa-bus nav-icon"></i> -->
                      <i class="fas fa-id-card nav-icon"></i>
                    </div>
                  </div>
                </div>
                 <div class="col-lg-4 col-6">
                  <div class="small-box bg-success">
                    <div class="inner">
                      <h3>{{ getVehicleCount(2); }}</h3>
                      <p>Bus</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-bus-alt nav-icon"></i>
                    </div>
                  </div>
                </div>

                <div class="col-lg-4 col-6">
                  <div class="small-box bg-success">
                    <div class="inner">
                      <h3>{{ getVehicleCount(1); }}</h3>
                      <p>Van</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-shuttle-van nav-icon"></i>
                    </div>
                  </div>
                </div>

                <div class="col-lg-4 col-6">
                  <div class="small-box bg-success">
                    <div class="inner">
                      <h3>{{ getVehicleCount(3); }}</h3>
                      <p>Mini Bus/Modernize Jeepney</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-bus nav-icon"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-5">
                <div class="card">
                  <div class="card-header">Today's Passengers</div>
                  <div class="card-body" style="height:327px;">
                    @if(empty(getTransactionMaleFemale('male')) && empty(getTransactionMaleFemale('female')))
                    <h3 class="text-muted text-center">No Passengers found.</h3>
                    @else
                      <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    @endif

                  </div>
                </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <div class="card">
                <div class="card-header">Today's Transactions <b>({{ date('Y-m-d') }})</b>
                  <a target="blank" class="btn btn-primary float-right" href="{{ route('admin.transaction.pdf') }}"><i class="fa fa-print"></i> Print Report</a>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-hover table-bordered table-stripped">
                        <thead>
                            <tr>
                                <th colspan="2">Date: {{ date('Y-m-d') }}</th>
                                <th colspan="7" class="text-center">DISPATCHER REPORT</th>
                                <th colspan="1">SHIFT:</th>
                            </tr>
                            <tr>
                                <th>No.</th>
                                <th>Name of Driver</th>
                                <th>Plate No.</th>
                                <th>Route</th>
                                <th>No. of Passengers</th>
                                <th>Time of Arrival</th>
                                <th>Time of Departure</th>
                                <th>Male Passengers</th>
                                <th>Female Passengers</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php $i = 1; @endphp
                            @foreach(getTodays() as $dt)
                                <tr>
                                    <td>{{ $i }}</td>
                                    <td>{{ $dt->driver->fullname }}</td>
                                    <td>{{ $dt->driver->plate_number }}</td>
                                    <td>{{ $dt->routes }}</td>
                                    <td>{{ (intval($dt->male) + intval($dt->female))  }}</td>
                                    <td>{{ $dt->arrival_time }}</td>
                                    <td>{{ $dt->departure_time }}</td>
                                    <td>{{ $dt->male }}</td>
                                    <td>{{ $dt->female }}</td>
                                    <td>{{ $dt->status_text }}</td>
                                </tr>
                                @php $i++ @endphp
                            @endforeach
                        </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        @elseif(auth()->user()->type === 4)
        <div class="row" id="transactions_code">
          @forelse(getMyRoute() as $routes)
            <div class="col-lg-4 col-12">
              <div class="small-box {{ $routes->status_color }}">
                <div class="inner">
                  <p class="m-0">Status: {{ $routes->status_text }}</p>
                  <h3>{{ $routes->routes }}</h3>
                  <p class="m-0">Male: <b>{{ $routes->male }}</b></p>
                  <p class="m-0">Female: <b>{{ $routes->female }}</b></p>
                  <p class="m-0">Total Passengers: <b>{{ ($routes->male + $routes->female) }}</b></p>
                </div>
                <div class="icon">
                  <i class="fas fa-map-marker-alt nav-icon"></i>
                </div>
                <a href="#" onclick="generateQr('{{ $routes->id }}', '{{ $routes->routes }}');" class="small-box-footer">View QR Code</a>
              </div>
            </div>
            @empty
          @endforelse
        </div>
        @endif
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

@endsection

@push('page-modals')
 <div class="modal fade" role="dialog" id="modal_qrcode">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title" >
          <h3 ><i class="fas fa-map-marker-alt nav-icon"></i> <span id="route_title"></span></h3>
          </div>
          <button class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <div id="trans_qrcode" class="text-center"></div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-success" onclick="location.reload();">Done</button>
        </div>
      </div>
    </div>
  </div>
@endpush

@push('js-scripts')
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<script>
   var qrcode = new QRCode("trans_qrcode", {
          text: 'test',
          width: 300,
          height: 300,
          colorDark : "#000000",
          colorLight : "#ffffff",
          correctLevel : QRCode.CorrectLevel.H
      });

    function generateQr(text, title){
      $("#route_title").text(title);
       qrcode.clear();
       qrcode.makeCode(text);
       $("div#trans_qrcode > img").removeAttr('style');
       $("#modal_qrcode").modal({'backdrop': 'static'});
    }



    function chart_render(){
      var donutData = {
      labels: [
          'Male',
          'Female',
      ],
      datasets: [
        {
          data: ['{{ getTransactionMaleFemale('male') }}','{{ getTransactionMaleFemale('female') }}'],
          backgroundColor : ['#007BFF', '#e85aa8'],
        }
      ]
    }

      var pieChartCanvas = $('#pieChart').get(0).getContext('2d');
      var pieData        = donutData;
      var pieOptions     = {
        maintainAspectRatio : false,
        responsive : true,
      }
      //Create pie or douhnut chart
      // You can switch between pie and douhnut using the method below.
      new Chart(pieChartCanvas, {
        type: 'pie',
        data: pieData,
        options: pieOptions
      })
    }

    chart_render();


</script>

@endpush

resources/views/admin/scan.blade.php
@extends('admin.layout.app')
@section('title', 'Scanner')

@push('styles')
<style type="text/css">
  #reader{
    width: auto !important; position: relative; padding: 0px; border: 1px solid silver;
  }
  button{
    display: inline-block;
    font-weight: 400;
    color: #212529;
    text-align: center;
    vertical-align: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: transparent;
    border: 1px solid transparent;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: 0.25rem;
    transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }
  button {
  color: #fff;
  background-color: #007bff;
  border-color: #007bff;
  box-shadow: none;
}

  button:hover {
  color: #fff;
  background-color: #0069d9;
  border-color: #0062cc;
}

  button:focus{
  color: #fff;
  background-color: #0069d9;
  border-color: #0062cc;
  box-shadow: 0 0 0 0 rgba(38, 143, 255, 0.5);
}
</style>

@endpush

@section('content')

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      	<div class="row">
      		<div class="col-lg-12">
              <div style="width:500px;" id="reader"></div>
            </div>
      	</div>
      </div>
    </section>
    <!-- /.content -->

@endsection

@push('page-modals')

@endpush

@push('js-scripts')
  

<script type="text/javascript">

  function onScanSuccess(qrCodeMessage) {
    // alert(qrCodeMessage);
    
    $.ajax({
        type:"get",
        url:'{{ route('admin.scanning') }}',
        data:{id:qrCodeMessage},
        dataType:'json',
        beforeSend:function(){
          $("button").click();
        },
        success:function(response){
          // console.log(response);
         if (response.status == true) {
            // swal("Success", response.message, "success");
             Swal.fire({
              position: 'center',
              icon: 'success',
              title: response.message,
              showConfirmButton: false,
              timerProgressBar: true,
              timer: 5000
            }).then(() => {
              location.reload();
            });
         }else if (response.status == false) {
            Swal.fire({
              position: 'center',
              icon: 'error',
              title: response.message,
              showConfirmButton: false,
              timerProgressBar: true,
              timer: 5000
            }).then(() => {
              location.reload();
            });

         }else{
          console.log('failed here');
          console.log(response);
         }
        },
        error: function(error){
          console.log(error);
        }
      });
      


  }
  function onScanError(errorMessage) {
    //handle scan error
    console.log(errorMessage);
  }
  var html5QrcodeScanner = new Html5QrcodeScanner(
      "reader", { fps: 10, qrbox: 250 });
  html5QrcodeScanner.render(onScanSuccess, onScanError);
</script>
@endpush