routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\userManagementController;
use App\Http\Controllers\Admin\profileSettingsController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\VehicleController;
use App\Http\Controllers\Admin\TransactionController;

/* Admin Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
	
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('scan', [HomeController::class, 'scanner'])->name('scanner');
    Route::get('scan-code', [HomeController::class, 'scanCode'])->name('scanning');
 
    Route::group(['prefix' => 'users', 'as' => 'user_management.'], function(){
		Route::controller(userManagementController::class)->group(function () {
			Route::get('/manage/{type}', 'index')->name('index');
			Route::post('store', 'store')->name('store');
			Route::get('list/{type}', 'list')->name('list');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('destroy/{id?}', 'destroy')->name('destroy');
			Route::post('/upload', 'uploadFile')->name('upload.file');
		});
	});

	Route::group(['prefix' => 'profile-settings', 'as' => 'profile_settings.'], function(){
		Route::controller(profileSettingsController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('change_password', 'change_password')->name('change_password');
			Route::post('store', 'store')->name('store');
		});
	});

	Route::group(['prefix' => 'vehicles', 'as' => 'vehicles.'], function(){
		Route::controller(VehicleController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	Route::group(['prefix' => 'transactions', 'as' => 'transaction.'], function(){
		Route::controller(TransactionController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('download', 'generatePDF')->name('pdf');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');

		});
	});

	
});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'index'])->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');




//Authentications
Route::group(['prefix'=> 'auth'], function(){

    Route::name('auth.')->group(function () {
        // For Login
        Route::controller(AuthController::class)->group(function () {
             Route::post('request', 'authenticate')->name('authenticate');
             Route::get('forget-password', 'forget_password')->name('forget.password');
             Route::post('forget-password/submit', 'forget_password_submit')->name('forget.password.submit');
             Route::get('change-password/{token?}', 'change_password')->name('change.password');
             Route::post('change-password/submit', 'change_password_submit')->name('change.password.submit');
             Route::post('update_pass', 'update_pass')->name('update.password');
        });

        // // For Forgot Password
        // Route::controller(ForgotPasswordController::class)->group(function () {
        //     Route::get('forget-password', 'index')->name('forget.password.get');
        //     Route::post('forget-password','store')->name('forget.password.post');
        //     Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        //     Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
        //     Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
        //     Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
        // });
        
    });
}); 




?>

app/Models/Vehicle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    use HasFactory;

    const VAN = 1;
    const BUS = 2;

    protected $table = 'vehicles';
    protected $fillable = [
        'color',
		'vehicle_model',
		'plate_number',
		'type',
    ];

    protected $appends = ['type_text'];


    public function getTypeTextAttribute(){
    	return $this->vehicleTypes()[$this->type];
    }

    public static function vehicleTypes(){
    	return [1 => 'van', 2 => 'bus'];
    }

}

app/Http/Controllers/Admin/VehicleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Vehicle;
use App\Models\User;
use Validator;

class VehicleController extends Controller
{
	public function index(){
		$vehicles = Vehicle::vehicleTypes();
		return view('admin.Vehicle.index', compact('vehicles'));
	}

	public function list(){
		$vehicles = User::where('type', 4)->get();
		return response()->json(['status' => true, 'data' => $vehicles ]);
	}

	public function save(Request $request, $id = ""){
		$validator = Validator::make($request->all(), [
			'color' => 'required',
			'vehicle_model' => 'required',
			'plate_number' => 'required',
			'type' => 'required',
		]);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			if(!empty($id)){
				$vehicles = Vehicle::where('id', $id)->update([
					'color' => $request->get('color'),
					'vehicle_model' => $request->get('vehicle_model'),
					'plate_number' => $request->get('plate_number'),
					'type' => $request->get('type'),
				]);
				if($vehicles){
					return response()->json(['status' => true, 'message' => 'vehicles saved successfully!']);
				}
			}else{
				$vehicles = Vehicle::create([
					'color' => $request->get('color'),
					'vehicle_model' => $request->get('vehicle_model'),
					'plate_number' => $request->get('plate_number'),
					'type' => $request->get('type'),
				]);
				if($vehicles){
					return response()->json(['status' => true, 'message' => 'vehicles updated successfully!']);
				}
			}
		}
	}

	public function find($id){
		$vehicles = Vehicle::findOrFail($id);
		return response()->json(['status' => true, 'data' => $vehicles ]);
	}

	public function delete($id){
		$vehicles = Vehicle::findOrFail($id);
		if($vehicles->delete()){
			return response()->json(['status' => true, 'message' => 'Record deleted successfully!' ]);
		}
	}

}

resources/views/admin/Vehicle/index.blade.php
@extends('admin.layout.app')
@section('title', 'Vehicle Management')

@push('styles')

<style>
    
</style>

@endpush

@section('content')

    <div class="container-fluid">
      <div class="card d-none">
        <div class="card-header" onclick="$('#minimize_filter').click()" >
          <h5 class="card-title">Record Filter</h5>
          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
            
            </button>
          </div>
        </div>
        
        <div class="card-body">
          <div class="row">
            <div class="position-relative mb-2 col-md-4">
              <label>Fullname or Address</label>
              <input type="text" name="filter" id="filter" class="form-control" placeholder="Search here">
              
            </div>
          </div>
          
        </div>
        <div class="card-footer text-right">
          <button type="button" class="btn btn-secondary" data-card-widget="collapse" id="minimize_filter">
          <i class="fa fa-minus"></i> Minimize Filter
          </button>
          <button type="button" id="refresh-filter" class="btn btn-success btn-md"><i class="fa fa-sync-alt"></i> Refresh Filter</button>
          <button type="button" class="btn btn-info btn-md" onclick="submit_filter()"><i class="fa fa-search"></i> Run Filter</button>
        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
          <table class="table table-bordered table-hove" id="tbl_user_accounts" style="width: 100%;"></table>
        </div>
      </div>
    </div>
  </div>


  <!-- modal here -->
    <form class="needs-validation" id="vehicle_form" action="{{ route('admin.vehicles.save') }}" novalidate>
      <div class="modal fade" tabindex="-1" role="dialog" id="modal_vehicle_form" data-backdrop="static">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modal_vehicle_form_title">Add Vehicles</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
              <div class="row">
                @csrf
                <input type="hidden" name="id" id="id" />
                <div class="col-md-12 mb-2">
                  <label>Color</label>
                  <input type="text" name="color" id="color" class="form-control " required  Enter color/>
                </div>
                <div class="col-md-12 mb-2">
                  <label>Vehicle model</label>
                  <input type="text" name="vehicle_model" id="vehicle_model" class="form-control " required  Enter vehicle model/>
                </div>
                <div class="col-md-12 mb-2">
                  <label>Plate number</label>
                  <input type="text" name="plate_number" id="plate_number" class="form-control " required  Enter plate number/>
                </div>
                <div class="col-md-12 mb-2">
                  <label>Type</label>
                  <select name="type" id="type" class="form-control " required>
                    <option selected="" disabled="">Please select vehicle type</option>
                    @foreach($vehicles as $key => $row)
                    <option value="{{ $key }}">{{ ucfirst($row) }}</option>
                    @endforeach
                  </select>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-success" id="vehicle_form_btn" >Save</button>
            </div>
          </div>
        </div>
      </div>
    </form>

   <div class="modal" tabindex="-1" role="dialog" id="user_details" data-backdrop="static">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">User Account</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true">&times;</button>
          </div>
          <div class="modal-body">
            <p>Please take a screenshot or copy the user account.</p>
            <p>Username: <span id="username_account"></span></p>
            <p>Password: <span id="password_account"></span></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-success">Ok</button>
          </div>
        </div>
      </div>
    </div>
  <!-- modal here -->
@endsection

@push('page-modals')

@endpush

@push('js-scripts')
<script type="text/javascript">

  // $("#user_management_form").on('submit', function(e){
  //   var mydata = $(this).serialize();
  //   let url = $(this).attr('action');
  //   e.stopPropagation();
  //   e.preventDefault(e);

  //   $.ajax({
  //     headers: {
  //                   'X-CSRF-TOKEN': "{{csrf_token()}}",
  //               },
  //     type:"post",
  //     url:url,
  //     data:mydata,
  //     cache:false,
  //     beforeSend:function(){
  //         //<!-- your before success function -->
  //         $('#btn_submit').prop('disabled', true);
  //         $('#btn_submit').text('Please wait...');
  //     },
  //     success:function(response){
  //         //console.log(response)
  //       if(response.status == true){
  //         Swal.fire({
  //                   position: 'center',
  //                   icon: 'success',
  //                   title: response.message,
  //                   showConfirmButton: false,
  //                   timer: 1500
  //                 })
          
  //         validation('user_management_form', response.errors);
  //         show_user_accounts();
  //         $('#modal_add_edit').modal('hide');


  //         $("#username_account").text(response.details.username);
  //         $("#password_account").text(response.details.password);
  //         $("#user_details").modal('show');


  //       }else{
  //         validation('user_management_form', response.errors);
  //       }
  //       $('#btn_submit').prop('disabled', false);
  //       $('#btn_submit').text('Save');
  //     },
  //     error:function(error){
  //       $('#btn_submit').prop('disabled', false);
  //       $('#btn_submit').text('Save');
  //       console.log(error);
  //     }
  //   });
  // });

  $("#vehicle_form").on('submit', function(e){
    e.preventDefault();
    let id = $('#id').val();
    let url = $(this).attr('action');
    let formData = $(this).serialize();
    $.ajax({
      type:"POST",
      url:url+'/'+id,
      data:formData,
      dataType:'json',
      beforeSend:function(){
        $('#vehicle_form_btn').prop('disabled', true);
      },
      success:function(response){
        // console.log(response);
        if (response.status == true) {
          $('#modal_vehicle_form').modal('hide');
           Swal.fire({
            position: 'center',
            icon: 'success',
            title: response.message,
            showConfirmButton: false,
            timer: 1500
          });
        show_user_accounts();
        }else{
          console.log(response);
        }
          validation('vehicle_form', response.error);
          $('#vehicle_form_btn').prop('disabled', false);
      },
      error: function(error){
        $('#vehicle_form_btn').prop('disabled', false);
        console.log(error);
      }
    });
  });

  function add_vehicles(){
    $("#id").val('');
    $('#color').val('');
    $('#vehicle_model').val('');
    $('#plate_number').val('');
    $('#type').val('');
    $('.modal-title').html('Add Vehicle');
    $("#modal_vehicle_form").modal('show');
  }


  function edit_vehicles(id){
    $.ajax({
      type:"GET",
      url:"{{ route('admin.vehicles.find') }}/"+id,
      data:{},
      dataType:'json',
      beforeSend:function(){
      },
      success:function(response){
        // console.log(response);
        if (response.status == true) {
          $('#id').val(response.data.id);
          $('#color').val(response.data.color);
          $('#vehicle_model').val(response.data.vehicle_model);
          $('#plate_number').val(response.data.plate_number);
          $('#type').val(response.data.type);
          $('.modal-title').html('Edit Vehicle');
          $('#modal_vehicle_form').modal('show');
        }else{
          console.log(response);
        }
      },
      error: function(error){
        console.log(error);
      }
    });
  }

  $('#refresh-filter').on('click', function(){
    $('#filter').val('');
    submit_filter();
  });

  function submit_filter(){
    show_user_accounts();
    
  }

  show_user_accounts();
  var tbl_user_accounts;
  function show_user_accounts(){
    if (tbl_user_accounts) {
      tbl_user_accounts.destroy();
    }
      tbl_user_accounts = $('#tbl_user_accounts').DataTable({
      dom: 'Bfrtip',
      dom: "<'row'<'col-sm-12 col-md-6'B><'col-sm-12 col-md-6'f>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
          buttons: [
          ],
      language: {
      "emptyTable": "No data available"
      },
    ajax: {
          url: "{{ route('admin.vehicles.list') }}",
          data: {filter : $('#filter').val()},
      },
      columns: [{
      className: '',
      "data": "fullname",
      "title": "Fullname",
      "orderable": false,
    },{
      className: '',
      "data": "plate_number",
      "title": "Plate #",
      "orderable": false,
    },{
      className: '',
      "data": "vehicle_model",
      "title": "Model",
      "orderable": false,
    },{
      className: '',
      "data": "color",
      "title": "Color",
      "orderable": false,
    },{
      className: '',
      "data": "vehicle_type",
      "title": "Type",
      "orderable": false,
    }
    ]
    });
  }




  function delete_vehicle(id){

    Swal.fire({
        title: 'Are you sure?',
        text: "This user will be deleted!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            headers: {
                    'X-CSRF-TOKEN': "{{csrf_token()}}",
                },
        type:"delete",
        url:"{{ route('admin.vehicles.delete') }}/"+id,
        data:{},
        dataType:'json',
        beforeSend:function(){
        },
        success:function(response){
          // console.log(response);
         if (response.status == true) {
          show_user_accounts();
         }else{
          console.log(response);
         }
        },
        error: function(error){
          console.log(error);
        }
      });

          Swal.fire(
            'Deleted!',
            'User has been deleted.',
            'success'
          )
        }
      })

    
  }

  
</script>
@endpush