routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\userManagementController;
use App\Http\Controllers\Admin\profileSettingsController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\VehicleController;
use App\Http\Controllers\Admin\TransactionController;

/* Admin Routes */
Route::name('admin.')->middleware(['auth','role:admin'])->group(function () {
	
    Route::get('', [HomeController::class, 'index'])->name('home');
    Route::get('scan', [HomeController::class, 'scanner'])->name('scanner');
    Route::get('scan-code', [HomeController::class, 'scanCode'])->name('scanning');
 
    Route::group(['prefix' => 'users', 'as' => 'user_management.'], function(){
		Route::controller(userManagementController::class)->group(function () {
			Route::get('/manage/{type}', 'index')->name('index');
			Route::post('store', 'store')->name('store');
			Route::get('list/{type}', 'list')->name('list');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('destroy/{id?}', 'destroy')->name('destroy');
			Route::post('/upload', 'uploadFile')->name('upload.file');
		});
	});

	Route::group(['prefix' => 'profile-settings', 'as' => 'profile_settings.'], function(){
		Route::controller(profileSettingsController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::post('change_password', 'change_password')->name('change_password');
			Route::post('store', 'store')->name('store');
		});
	});

	Route::group(['prefix' => 'vehicles', 'as' => 'vehicles.'], function(){
		Route::controller(VehicleController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');
		});
	});


	Route::group(['prefix' => 'transactions', 'as' => 'transaction.'], function(){
		Route::controller(TransactionController::class)->group(function () {
			Route::get('', 'index')->name('index');
			Route::get('list', 'list')->name('list');
			Route::get('download', 'generatePDF')->name('pdf');
			Route::post('save/{id?}', 'save')->name('save');
			Route::get('find/{id?}', 'find')->name('find');
			Route::delete('delete/{id?}', 'delete')->name('delete');

		});
	});

	
});
?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'index'])->name('login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');




//Authentications
Route::group(['prefix'=> 'auth'], function(){

    Route::name('auth.')->group(function () {
        // For Login
        Route::controller(AuthController::class)->group(function () {
             Route::post('request', 'authenticate')->name('authenticate');
             Route::get('forget-password', 'forget_password')->name('forget.password');
             Route::post('forget-password/submit', 'forget_password_submit')->name('forget.password.submit');
             Route::get('change-password/{token?}', 'change_password')->name('change.password');
             Route::post('change-password/submit', 'change_password_submit')->name('change.password.submit');
             Route::post('update_pass', 'update_pass')->name('update.password');
        });

        // // For Forgot Password
        // Route::controller(ForgotPasswordController::class)->group(function () {
        //     Route::get('forget-password', 'index')->name('forget.password.get');
        //     Route::post('forget-password','store')->name('forget.password.post');
        //     Route::get('reset-password/{token}', 'showResetPasswordForm')->name('reset.password.get');
        //     Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
        //     Route::get('reset-password-success/', 'resetSuccess')->name('reset.password.success');
        //     Route::get('reset-password-sent/', 'sentResetPasswordPage')->name('reset.password.sent');
        // });
        
    });
}); 




?>

resources/views/admin/layout/app.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title> @yield('title')</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('img/stgo.png') }}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">

    <!-- Datatables -->
    <link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables-new/datatables.min.css') }}"/>

    <!-- Lada Button -->
    <link type="text/css" href="{{ asset('plugins/ladda/ladda-themeless.min.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
      <!-- Toastr -->
    <link rel="stylesheet" href="{{ asset('plugins/toastr/toastr.min.css') }}">
  
    <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">

    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
    <style type="text/css">
      input::-webkit-outer-spin-button,
      input::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
      }

      /* Firefox */
      input[type=number] {
        -moz-appearance: textfield;
      }


    </style>
    @stack('styles')    
    <!-- CUSTOM CSS FILES HERE -->
</head>
    
<body class="hold-transition sidebar-mini sidebar-collapse">

<div class="wrapper">

  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="" src="{{ asset('img/stgo.png') }}" alt="AdminLTELogo" height="150" width="150">
  </div>

    @include('admin.layout.navbar')

    @include('admin.layout.sidebar')

    <!-- Content Wrapper. Contains page content -->

      <div class="content-wrapper">
        @include('admin.layout.breadcrumb')
        @yield('content')
      </div>

    <!-- /.content-wrapper -->
    @include('admin.layout.back_to_top')
    @include('admin.layout.footer')

</div>

<!-- Global Modals -->
@stack('page-modals')
<!-- End Global Modals -->

<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- ladda -->
<script src="{{ asset('plugins/ladda/spin.min.js') }}"></script>
<script src="{{ asset('plugins/ladda/ladda.min.js') }}"></script>
<script src="{{ asset('plugins/ladda/ladda.jquery.min.js') }}"></script>

<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>

<script src="{{ asset('plugins/toastr/toastr.min.js') }}"></script>

<script src="{{ asset('plugins/datatables-new/datatables.min.js') }}"></script>

<!-- SOLUTION FOR EXPORT COMPLEX HEADERS COMMENT IF SOMETHING GOES WRONG - RAVEN -->
<script src="{{ asset('plugins/datatables-new/Buttons-2.2.3/js/dataTables.buttons.js') }}"></script>
<script src="{{ asset('plugins/datatables-new/Buttons-2.2.3/js/buttons.html5.js') }}"></script>
<script src="{{ asset('plugins/datatables-new/Buttons-2.2.3/js/buttons.print.js') }}"></script>
<!-- SOLUTION FOR EXPORT COMPLEX HEADERS COMMENT IF SOMETHING GOES WRONG - RAVEN -->

<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>

<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>

<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>

<!-- Custom Js -->
<script src="{{ asset('custom/validation.js') }}"></script>
<script src="{{ asset('custom/qr.js') }}"></script>
<script src="{{ asset('custom/scanner.js') }}"></script>

<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>

<script>

    var Toast = Swal.mixin({
      toast: true,
      position: 'toast-top-center',
      showConfirmButton: false,
      timer: 3000
    });

  class custom_err{
      static clear(form_object){//call this using custom_err.clear(form_object)
          form_object.find('input, textarea, select, div, checkbox').removeClass('is-invalid');
      }


      //use this when you want to use the loop here directly WE USE THIS BY DEFAULT
      static display_all(errors=[],form_object){
        $.each(errors, function(key, value) {
            custom_err.display(form_object, key, value[0]);
        });
      }

      //use this when you're using the loop in error condition WE USE THIS WHEN WE WANT TO ALTER SOMETHING
      static display(form_object, field_name, error_message){//call this using custom_err.display(form_object, field_name, error_message)
          form_object.find('[name="'+field_name+'"]').addClass('is-invalid');
          form_object.find('[name="'+field_name+'"]').parent().find('.invalid-feedback').text(error_message);
      }
      
  }

  $(document).on('select2:open', (e) => {
    const selectId = e.target.id
      $(".select2-search__field[aria-controls='select2-" + selectId + "-results']").each(function (
          key,
          value,
      ){
          value.focus();
      })
  })

  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

  window.Laravel = {!! json_encode(['csrfToken' => csrf_token(),]) !!};

</script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
@stack('js-scripts') 
</body>
</html>

resources/views/admin/layout/back_to_top.blade.php
<!-- <a id="back-to-top" href="#" class="btn btn-primary back-to-top" role="button" aria-label="Scroll to top">
  <i class="fas fa-chevron-up"></i>
</a> -->

resources/views/admin/layout/breadcrumb.blade.php
<section class="content-header breadcrumb sidebar-light-primary">
    <div class="container-fluid">
      <div class="row breadcrumb-row-content">
        <div class="col-sm-6">
          <h1 class="m-0">{!! View::getSection('title') !!}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ route('admin.home') }}">Home</a></li>
            <li class="breadcrumb-item active">{{ View::getSection('title') }}</li>
          </ol>
        </div>
      </div>
    </div>
</section>

resources/views/admin/layout/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer text-sm">
    <!-- Default to the left -->
    <!-- <strong>Copyright &copy; {{ date('Y') }} <a href="#">{{ config('app.name') }}</a>.</strong> All rights reserved. -->
</footer>

resources/views/admin/layout/navbar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark bg-primary">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{ route('logout') }}" class="nav-link">Logout</a>
      </li>
    </ul>
  </nav>
<!-- /.navbar -->

resources/views/admin/layout/sidebar.blade.php
 <!-- Main Sidebar Container old sidebar-dark-primary -->
  <aside class="main-sidebar sidebar-dark-primary elevation-1">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <img src="{{ asset('img/stgo.png') }}" alt="Company Logo" class="brand-image img-circle">
      <span class="brand-text font-weight-bold">E-Dispatching</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar text-sm">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
           <a href="">
             <img src="{{ Auth::user()->getAvatarImg() }}" class="img-circle elevation-2" alt="Employee Male Default">
           </a>
        </div>
        <div class="info">
          <a href="" class="d-block"><b>{{ auth()->user()->fullname }} <span class="badge badge-primary">{{ auth()->user()->getTypeText(auth()->user()->type) }}</span></b></a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column nav-compact" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{{ route('admin.home') }}" class="nav-link {{ (request()->is('dashboard'))? 'active': '' }}">
                <i class="fa fa-th nav-icon"></i>
                <p>Dashboard</p>
              </a>
            </li>

            @if(auth()->user()->type === 1)
            <li class="nav-item {{ (request()->is('dashboard/users/manage/dispatcher') || request()->is('dashboard/users/manage/monitor') || request()->is('dashboard/users/manage/driver'))? 'menu-open' : '' }}">
              <a href="#" class="nav-link {{ (request()->is('dashboard/users/manage/dispatcher') || request()->is('dashboard/users/manage/monitor') || request()->is('dashboard/users/manage/driver'))? 'active' : '' }}">
                <i class="nav-icon far fa-user"></i>
                <p>
                  User Accounts
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview ml-3" style="{{ (request()->is('dashboard/users/manage/dispatcher') || request()->is('dashboard/users/manage/monitor') || request()->is('dashboard/users/manage/driver'))? '' : 'display: none;' }} ">
                <li class="nav-item">
                  <a href="{{ route('admin.user_management.index', 'dispatcher') }}" class="nav-link {{ (request()->is('dashboard/users/manage/dispatcher'))? 'active': '' }}">
                    <i class="fa fa-people-arrows nav-icon"></i>
                    <p>Dispatcher</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('admin.user_management.index', 'monitor') }}" class="nav-link {{ (request()->is('dashboard/users/manage/monitor'))? 'active': '' }}">
                    <i class="fa fa-user-cog nav-icon"></i>
                    <p>Monitor</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('admin.user_management.index', 'driver') }}" class="nav-link {{ (request()->is('dashboard/users/manage/driver'))? 'active': '' }}">
                    <i class="far fa-id-card nav-icon"></i>
                    <p>Driver</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a href="{{ route('admin.vehicles.index') }}" class="nav-link {{ (request()->is('dashboard/vehicles'))? 'active': '' }}">
                <i class="fas fa-bus nav-icon"></i>
                <p>Vehicle</p>
              </a>
            </li>
            @endif
            @if(auth()->user()->type !== 4 && auth()->user()->type !== 1)
              <li class="nav-item">
                <a href="{{ route('admin.scanner') }}" class="nav-link {{ (request()->is('dashboard/scan'))? 'active': '' }}">
                  <i class="fas fa-qrcode nav-icon"></i>
                  <p>Scanner</p>
                </a>
              </li>
            @endif

            <li class="nav-item">
              <a href="{{ route('admin.transaction.index') }}" class="nav-link {{ (request()->is('dashboard/transactions'))? 'active': '' }}">
                <i class="fas fa-list nav-icon"></i>
                <p>Monitoring</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('admin.profile_settings.index') }}" class="nav-link {{ (request()->is('dashboard/profile-settings'))? 'active': '' }}">
                <i class="fas fa-cog nav-icon"></i>
                <p>Account Settings</p>
              </a>
            </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>